{
  description = "Tay's modern NixOS + Hyprland desktop";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";

    home-manager = {
      url = "github:nix-community/home-manager/release-26.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Latest stable Hyprland release at the time of this refresh.
    hyprland.url = "github:hyprwm/Hyprland/v0.56.2";

  };

  outputs = inputs@{ nixpkgs, home-manager, hyprland, ... }:
    let
      system = "x86_64-linux";

      mkSystem = { local, hardwareModule }: nixpkgs.lib.nixosSystem {
        inherit system;
        specialArgs = { inherit inputs local; };
        modules = [
          hardwareModule
          hyprland.nixosModules.default
          ./nixos/configuration.nix

          home-manager.nixosModules.home-manager
          {
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.backupFileExtension = "nixdots-backup";
            home-manager.extraSpecialArgs = { inherit inputs local; };
            home-manager.users.${local.username} = import ./home/home.nix;
          }
        ];
      };

      # Machine-specific files are generated by install.sh and stay local.
      haveLocalHost = builtins.pathExists ./hosts/local.nix
        && builtins.pathExists ./hosts/hardware-configuration.nix;
    in {
      nixosConfigurations = {
        # CI / clean-clone fixture: always evaluable and buildable.
        ci = mkSystem {
          local = import ./hosts/ci.nix;
          hardwareModule = ./hosts/ci-hardware.nix;
        };
      } // nixpkgs.lib.optionalAttrs haveLocalHost {
        # The real machine, only present after install.sh generated its files.
        nixdots = mkSystem {
          local = import ./hosts/local.nix;
          hardwareModule = ./hosts/hardware-configuration.nix;
        };
      };

      checks.${system}.ci-system =
        inputs.self.nixosConfigurations.ci.config.system.build.toplevel;
    };
}
