general {
    hide_cursor = true
    immediate_render = true
    ignore_empty_input = true
}

background {
    monitor =
    path = screenshot
    color = rgba(10, 11, 24, 1.0)
    blur_passes = 3
    blur_size = 8
    brightness = 0.55
    vibrancy = 0.15
}

label {
    monitor =
    text = cmd[update:1000] date +'%H:%M'
    color = rgb(238, 234, 247)
    font_size = 64
    font_family = Inter
    position = 0, 115
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +'%A, %d %B'
    color = rgba(201, 195, 216, 0.90)
    font_size = 16
    font_family = Inter
    position = 0, 65
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 54
    outline_thickness = 2
    outer_color = rgba(191, 140, 255, 0.90)
    inner_color = rgba(25, 20, 33, 0.88)
    font_color = rgb(238, 234, 247)
    font_family = Inter
    placeholder_text = <i>Password…</i>
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    rounding = 16
    position = 0, -25
    halign = center
    valign = center
}
